"""Make used_at nullable in user_recovery_keys

Revision ID: 0693d62be40a
Revises: 8913ee41095e
Create Date: 2025-12-20 00:59:07.695610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0693d62be40a'
down_revision: Union[str, Sequence[str], None] = '8913ee41095e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('prompts_user_id_fkey'), 'prompts', type_='foreignkey')
    op.create_foreign_key(None, 'prompts', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('user_recovery_keys', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='Used At')
    op.drop_constraint(op.f('user_recovery_keys_user_id_fkey'), 'user_recovery_keys', type_='foreignkey')
    op.create_foreign_key(None, 'user_recovery_keys', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_recovery_keys', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_recovery_keys_user_id_fkey'), 'user_recovery_keys', 'users', ['user_id'], ['id'])
    op.alter_column('user_recovery_keys', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='Used At')
    op.drop_constraint(None, 'prompts', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('prompts_user_id_fkey'), 'prompts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'conversations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
