"""Add deleted column to conversations and messages

Revision ID: 8913ee41095e
Revises: 
Create Date: 2025-12-19 21:28:40.223723

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8913ee41095e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column(
        'deleted', sa.Boolean(), nullable=False, server_default=sa.false(), comment='Soft delete flag'))
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='PK',
               existing_comment='Первичный ключ записи',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.alter_column('conversations', 'public_id',
               existing_type=sa.UUID(),
               comment='Public UUID of conversation',
               existing_comment='Публичный UUID чата',
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               comment='FK users.id',
               existing_comment='Внешний ключ к users.id',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Title of conversation',
               existing_comment='Заголовок чата',
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Created At',
               existing_comment='Дата создания записи')
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Updated At',
               existing_comment='Дата обновления записи')
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('messages', sa.Column(
        'deleted', sa.Boolean(), nullable=False, server_default=sa.false(), comment='Soft delete flag'))
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment='PK',
               existing_comment='Первичный ключ записи',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'public_id',
               existing_type=sa.UUID(),
               comment='Public UUID of message',
               existing_comment='Публичный UUID сообщения',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment='FK conversations.id',
               existing_comment='Внешний ключ к conversations.id',
               existing_nullable=False)
    op.alter_column('messages', 'sender_type',
               existing_type=postgresql.ENUM('USER', 'AI', name='message_sender_type'),
               comment='Sender: user, ai',
               existing_comment='Назначение файла: user, ai',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='Text of message',
               existing_comment='Текст сообщения',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Created At',
               existing_comment='Дата создания записи')
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Updated At',
               existing_comment='Дата обновления записи')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('prompts', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Prompt is default?')
    op.alter_column('prompts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='Created At')
    op.alter_column('prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='Updated At')
    op.drop_constraint(op.f('prompts_user_id_fkey'), 'prompts', type_='foreignkey')
    op.create_foreign_key(None, 'prompts', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('user_recovery_keys_user_id_fkey'), 'user_recovery_keys', type_='foreignkey')
    op.create_foreign_key(None, 'user_recovery_keys', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='PK',
               existing_comment='Первичный ключ записи',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'public_id',
               existing_type=sa.UUID(),
               comment='Public UUID of user',
               existing_comment='Публичный UUID пользователя',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Username',
               existing_comment='Никнейм пользователя',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User Email',
               existing_comment='Email пользователя',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='User password (hashed)',
               existing_comment='Хэшированный пароль пользователя',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Created At',
               existing_comment='Дата создания записи')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Updated At',
               existing_comment='Дата обновления записи')
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last Login At',
               existing_comment='Дата последнего входа в систему',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата последнего входа в систему',
               existing_comment='Last Login At',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Дата обновления записи',
               existing_comment='Updated At')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Дата создания записи',
               existing_comment='Created At')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Хэшированный пароль пользователя',
               existing_comment='User password (hashed)',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email пользователя',
               existing_comment='User Email',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Никнейм пользователя',
               existing_comment='Username',
               existing_nullable=False)
    op.alter_column('users', 'public_id',
               existing_type=sa.UUID(),
               comment='Публичный UUID пользователя',
               existing_comment='Public UUID of user',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Первичный ключ записи',
               existing_comment='PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_constraint(None, 'user_recovery_keys', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_recovery_keys_user_id_fkey'), 'user_recovery_keys', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'prompts', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('prompts_user_id_fkey'), 'prompts', 'users', ['user_id'], ['id'])
    op.alter_column('prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='Updated At')
    op.alter_column('prompts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='Created At')
    op.alter_column('prompts', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Prompt is default?')
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Дата обновления записи',
               existing_comment='Updated At')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Дата создания записи',
               existing_comment='Created At')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='Текст сообщения',
               existing_comment='Text of message',
               existing_nullable=False)
    op.alter_column('messages', 'sender_type',
               existing_type=postgresql.ENUM('USER', 'AI', name='message_sender_type'),
               comment='Назначение файла: user, ai',
               existing_comment='Sender: user, ai',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment='Внешний ключ к conversations.id',
               existing_comment='FK conversations.id',
               existing_nullable=False)
    op.alter_column('messages', 'public_id',
               existing_type=sa.UUID(),
               comment='Публичный UUID сообщения',
               existing_comment='Public UUID of message',
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment='Первичный ключ записи',
               existing_comment='PK',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('messages', 'deleted')
    op.drop_constraint(None, 'conversations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Дата обновления записи',
               existing_comment='Updated At')
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Дата создания записи',
               existing_comment='Created At')
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Заголовок чата',
               existing_comment='Title of conversation',
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Внешний ключ к users.id',
               existing_comment='FK users.id',
               existing_nullable=False)
    op.alter_column('conversations', 'public_id',
               existing_type=sa.UUID(),
               comment='Публичный UUID чата',
               existing_comment='Public UUID of conversation',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='Первичный ключ записи',
               existing_comment='PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.drop_column('conversations', 'deleted')
    # ### end Alembic commands ###
